# Generated by Django 5.0.3 on 2024-03-15 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('fecha_de_fabricacion', models.DateField()),
            ],
        ),
    ]
