# Generated by Django 5.0.3 on 2024-03-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_autos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='autos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos_images'),
        ),
    ]
