# Generated by Django 5.0.3 on 2024-03-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosextra',
            name='tipo_de_sangre',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
